name: Close issues labeled wontfix

on:
  issues:
    types: [labeled]

jobs:
  close-wontfix:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'wontfix'
    steps:
      - name: Close issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}